import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "openapi/docudevs-api",
    },
    {
      type: "category",
      label: "agent",
      items: [
        {
          type: "doc",
          id: "openapi/chat",
          label: "chat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-agent-status",
          label: "getAgentStatus",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "cases",
      items: [
        {
          type: "doc",
          id: "openapi/list-cases",
          label: "listCases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-case",
          label: "createCase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-case",
          label: "getCase",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-case",
          label: "updateCase",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/delete-case",
          label: "deleteCase",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/list-case-documents",
          label: "listCaseDocuments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/upload-case-document",
          label: "uploadCaseDocument",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-case-document",
          label: "getCaseDocument",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-case-document",
          label: "deleteCaseDocument",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/download-case-document",
          label: "downloadCaseDocument",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-document-summary",
          label: "getDocumentSummary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/list-case-summaries",
          label: "listCaseSummaries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/upload-case-document-legacy",
          label: "uploadCaseDocumentLegacy",
          className: "menu__list-item--deprecated api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Embedding Generations",
      items: [
        {
          type: "doc",
          id: "openapi/get-case-embedding-status",
          label: "getCaseEmbeddingStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/reindex-case-embeddings",
          label: "reindexCaseEmbeddings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/cancel-case-embedding-reindex",
          label: "cancelCaseEmbeddingReindex",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/retry-case-embedding-reindex",
          label: "retryCaseEmbeddingReindex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-embedding-overview",
          label: "getEmbeddingOverview",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "configuration",
      items: [
        {
          type: "doc",
          id: "openapi/list-configurations",
          label: "listConfigurations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-configuration",
          label: "getConfiguration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/save-configuration",
          label: "saveConfiguration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-configuration",
          label: "deleteConfiguration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/download-excel-template",
          label: "downloadExcelTemplate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/upload-excel-template",
          label: "uploadExcelTemplate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/download-lookup-file",
          label: "downloadLookupFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/upload-lookup-file",
          label: "uploadLookupFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-lookup-file",
          label: "deleteLookupFile",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "contract-analysis-runs",
      items: [
        {
          type: "doc",
          id: "openapi/create-contract-analysis-run",
          label: "createContractAnalysisRun",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-contract-analysis-run",
          label: "getContractAnalysisRun",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-contract-analysis-run-result",
          label: "getContractAnalysisRunResult",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "contract-analysis-reviews",
      items: [
        {
          type: "doc",
          id: "openapi/get-contract-analysis-run-reviews",
          label: "getContractAnalysisRunReviews",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/put-contract-analysis-run-review",
          label: "putContractAnalysisRunReview",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "document",
      items: [
        {
          type: "doc",
          id: "openapi/extract-acro-form-metadata",
          label: "extractAcroFormMetadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/analyze-document",
          label: "analyzeDocument",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/generate-schema",
          label: "generateSchema",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/ocr-document-sync",
          label: "ocrDocumentSync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/ocr-document",
          label: "ocrDocument",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/process-document",
          label: "processDocument",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/process-document-with-configuration",
          label: "processDocumentWithConfiguration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/upload-document",
          label: "uploadDocument",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/upload-files",
          label: "uploadFiles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/upload-files-sync",
          label: "uploadFilesSync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/upload-template",
          label: "uploadTemplate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "batch",
      items: [
        {
          type: "doc",
          id: "openapi/create-batch",
          label: "createBatch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/download-batch-lookup-file",
          label: "downloadBatchLookupFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/upload-batch-lookup-file",
          label: "uploadBatchLookupFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-batch-lookup-file",
          label: "deleteBatchLookupFile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/process-batch",
          label: "processBatch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/process-batch-with-configuration",
          label: "processBatchWithConfiguration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/schedule-batch",
          label: "scheduleBatch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/upload-batch-document",
          label: "uploadBatchDocument",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "track-changes",
      items: [
        {
          type: "doc",
          id: "openapi/extract-track-changes",
          label: "Extract tracked changes (insertions, deletions) and comments from a Word document.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Embedding Providers",
      items: [
        {
          type: "doc",
          id: "openapi/get-default-embedding-binding",
          label: "getDefaultEmbeddingBinding",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-default-embedding-binding",
          label: "updateDefaultEmbeddingBinding",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/list-embedding-providers",
          label: "listEmbeddingProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-embedding-provider",
          label: "createEmbeddingProvider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-embedding-provider",
          label: "getEmbeddingProvider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-embedding-provider",
          label: "deleteEmbeddingProvider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/update-embedding-provider",
          label: "updateEmbeddingProvider",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "integration",
      items: [
        {
          type: "doc",
          id: "openapi/list-connections",
          label: "listConnections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-connection",
          label: "createConnection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-connection",
          label: "getConnection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-connection",
          label: "updateConnection",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/delete-connection",
          label: "deleteConnection",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/list",
          label: "list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-or-update",
          label: "createOrUpdate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete",
          label: "delete",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "job",
      items: [
        {
          type: "doc",
          id: "openapi/get-dependencies",
          label: "getDependencies",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-figure-image",
          label: "getFigureImage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-figures-metadata",
          label: "getFiguresMetadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-image",
          label: "getImage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/list-jobs",
          label: "listJobs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-processing-params",
          label: "getProcessingParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-acro-form-metadata",
          label: "getAcroFormMetadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-document-outline",
          label: "getDocumentOutline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-pdf-acro-form-result",
          label: "getPdfAcroFormResult",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-pdf-acro-form-field-definitions",
          label: "getPdfAcroFormFieldDefinitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-source-locations",
          label: "getSourceLocations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-workbook-artifact",
          label: "Retrieve a plan, source-map, or bounded summary artifact published for this workbook result.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/result",
          label: "result",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/result-csv",
          label: "resultCsv",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/result-excel",
          label: "resultExcel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/result-json",
          label: "resultJson",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/result-schema",
          label: "resultSchema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-job-status",
          label: "getJobStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-trace",
          label: "getTrace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-job",
          label: "deleteJob",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/apply-pdf-acro-form-field-definitions",
          label: "applyPdfAcroFormFieldDefinitions",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "pipeline",
      items: [
        {
          type: "doc",
          id: "openapi/open-client-run",
          label: "openClientRun",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/fail-client-run",
          label: "failClientRun",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/put-client-node-result",
          label: "putClientNodeResult",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/refresh-client-run",
          label: "refreshClientRun",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-segment-status",
          label: "Segment-scoped status.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "knowledge-bases",
      items: [
        {
          type: "doc",
          id: "openapi/list-knowledge-bases",
          label: "listKnowledgeBases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/promote-knowledge-base",
          label: "promoteKnowledgeBase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-knowledge-base",
          label: "getKnowledgeBase",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/demote-knowledge-base",
          label: "demoteKnowledgeBase",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "knowledge-base-profiles",
      items: [
        {
          type: "doc",
          id: "openapi/get-contract-analysis-profile",
          label: "getContractAnalysisProfile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-contract-analysis-draft",
          label: "updateContractAnalysisDraft",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/generate-contract-analysis-profile",
          label: "generateContractAnalysisProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/apply-contract-analysis-generation",
          label: "applyContractAnalysisGeneration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-contract-analysis-generation-comparison",
          label: "getContractAnalysisGenerationComparison",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/publish-contract-analysis-profile",
          label: "publishContractAnalysisProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-contract-analysis-source-authority",
          label: "getContractAnalysisSourceAuthority",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/record-contract-analysis-source-authority-decision",
          label: "recordContractAnalysisSourceAuthorityDecision",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "contract-analysis-trials",
      items: [
        {
          type: "doc",
          id: "openapi/get-contract-analysis-test-suite",
          label: "getContractAnalysisTestSuite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-contract-analysis-test-suite",
          label: "updateContractAnalysisTestSuite",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/propose-contract-analysis-finding-test-case",
          label: "proposeContractAnalysisFindingTestCase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/create-contract-analysis-trial",
          label: "createContractAnalysisTrial",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-contract-analysis-trial",
          label: "getContractAnalysisTrial",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/attest-contract-analysis-trial",
          label: "attestContractAnalysisTrial",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "LLM Providers",
      items: [
        {
          type: "doc",
          id: "openapi/list-llm-keys",
          label: "listLlmKeys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-llm-key",
          label: "updateLlmKey",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/list-llm-providers",
          label: "listLlmProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-llm-provider",
          label: "createLlmProvider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-llm-provider",
          label: "getLlmProvider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-llm-provider",
          label: "deleteLlmProvider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/update-llm-provider",
          label: "updateLlmProvider",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "openapi/verify-llm-provider",
          label: "verifyLlmProvider",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "managed-execution",
      items: [
        {
          type: "doc",
          id: "openapi/list-managed-executions",
          label: "listManagedExecutions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/dispatch-managed-execution",
          label: "dispatchManagedExecution",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-managed-execution",
          label: "getManagedExecution",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/cancel-managed-execution",
          label: "cancelManagedExecution",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-managed-execution-logs",
          label: "getManagedExecutionLogs",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "members",
      items: [
        {
          type: "doc",
          id: "openapi/list-1",
          label: "list_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/invite",
          label: "invite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/accept",
          label: "accept",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-join-policy",
          label: "getJoinPolicy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/set-join-policy",
          label: "setJoinPolicy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/remove",
          label: "remove",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/update",
          label: "update",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Model Credentials",
      items: [
        {
          type: "doc",
          id: "openapi/list-model-credentials",
          label: "listModelCredentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-model-credential",
          label: "createModelCredential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-model-credential",
          label: "getModelCredential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-model-credential",
          label: "deleteModelCredential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/update-model-credential",
          label: "updateModelCredential",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "openapi/disable-model-credential",
          label: "disableModelCredential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/enable-model-credential",
          label: "enableModelCredential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/rotate-model-credential",
          label: "rotateModelCredential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/validate-model-credential",
          label: "validateModelCredential",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Azure OCR Providers",
      items: [
        {
          type: "doc",
          id: "openapi/list-ocr-keys",
          label: "listOcrKeys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-ocr-key",
          label: "updateOcrKey",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/list-ocr-providers",
          label: "listOcrProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-ocr-provider",
          label: "createOcrProvider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-ocr-provider",
          label: "getOcrProvider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-ocr-provider",
          label: "deleteOcrProvider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/update-ocr-provider",
          label: "updateOcrProvider",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "operations",
      items: [
        {
          type: "doc",
          id: "openapi/submit-operation",
          label: "submitOperation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-operation-status",
          label: "getOperationStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-operation-result",
          label: "getOperationResult",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-generative-task",
          label: "createGenerativeTask",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "settings",
      items: [
        {
          type: "doc",
          id: "openapi/settings",
          label: "settings",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "webhook",
      items: [
        {
          type: "doc",
          id: "openapi/get-webhook",
          label: "getWebhook",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-webhook",
          label: "updateWebhook",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "sso",
      items: [
        {
          type: "doc",
          id: "openapi/get-settings",
          label: "getSettings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/checkout",
          label: "checkout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/update-config",
          label: "updateConfig",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/discovery",
          label: "discovery",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/add-domain",
          label: "addDomain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/delete-domain",
          label: "deleteDomain",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/verify-domain",
          label: "verifyDomain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/portal",
          label: "portal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/sync",
          label: "sync",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "submission-portals",
      items: [
        {
          type: "doc",
          id: "openapi/list-portals",
          label: "listPortals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/create-portal",
          label: "createPortal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-by-slug",
          label: "getBySlug",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-default-for-configuration",
          label: "getDefaultForConfiguration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-portal",
          label: "getPortal",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/update-portal",
          label: "updatePortal",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/delete-portal",
          label: "deletePortal",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/submit",
          label: "submit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/get-record",
          label: "getRecord",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/download",
          label: "download",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "template",
      items: [
        {
          type: "doc",
          id: "openapi/fill",
          label: "fill",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/list-templates",
          label: "listTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/metadata",
          label: "metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/delete-template",
          label: "deleteTemplate",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/upload-template-images",
          label: "uploadTemplateImages",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "openapi/lookup",
          label: "lookup",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/get-current-user",
          label: "getCurrentUser",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
