import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Getting Started - Clear onboarding path
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false, // Keep open for new users
      items: [
        'getting-started/quick-start',      // NEW: 5-minute tutorial
        'basics/install',                   // EXISTING: Installation guide
        'getting-started/first-document',   // NEW: Detailed walkthrough
      ],
    },

    // Core Features - Main functionality
    {
      type: 'category',
      label: 'Core Features',
      items: [
        'basics/SimpleDocuments',           // EXISTING: Core document processing
        'basics/PlainOCR',                  // EXISTING: OCR-only processing
        'core/ai-analysis',                 // NEW: AI document analysis and generative tasks
        'templates/Templates',              // EXISTING: Template management
        'core/schema-generation',           // NEW: AI schema generation
      ],
    },

    // Advanced Features - Power user functionality
    {
      type: 'category',
      label: 'Advanced Features',
      items: [
        'advanced/cases',                   // NEW: Document collections
        'configuration/Configuration',      // EXISTING: Named configurations
        'advanced/operations',              // NEW: Error analysis & operations
      ],
    },

    // Integration & Best Practices - Removed temporarily
    // TODO: Add integration guides when more specific patterns emerge

    // Reference - Technical details
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/sdk-methods',            // NEW: Complete SDK reference
        'reference/cli-reference',          // NEW: CLI command reference
        'reference/error-codes',            // NEW: Error reference
        'reference/limits-quotas',          // NEW: Platform limits
      ],
    },
  ],

  // API Reference - Auto-generated
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'openapi',
    },
  ],
};

export default sidebars;
