import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Basics',
      items: [
        'basics/install',
        'basics/SimpleDocuments',
        'templates/Templates',
        'configuration/Configuration'
      ],
    },
    // ...other categories or items...
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'openapi', // This should match the outputDir in your docusaurus.config.ts
    },
  ],
};

export default sidebars;
