openapi: 3.1.0
info:
  title: DocuDevs API
  description: DocuDevs Document processing API. Easiest way to convert your documents
    to data
  version: "0.1"
paths:
  /configuration:
    get:
      tags:
        - configuration
      operationId: listConfigurations
      responses:
        "200":
          description: listConfigurations 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NamedConfiguration"
  /configuration/{name}:
    get:
      tags:
        - configuration
      operationId: getConfiguration
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: getConfiguration 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadCommand"
    post:
      tags:
        - configuration
      operationId: saveConfiguration
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadCommand"
        required: true
      responses:
        "200":
          description: saveConfiguration 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NamedConfiguration"
    delete:
      tags:
        - configuration
      operationId: deleteConfiguration
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: deleteConfiguration 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unit"
  /document/process/{guid}:
    post:
      tags:
        - document
      operationId: processDocument
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            type: string
        - name: configuration
          in: query
          schema:
            type:
              - string
              - "null"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadCommand"
      responses:
        "200":
          description: processDocument 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
  /document/upload:
    post:
      tags:
        - document
      operationId: uploadDocument
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                document:
                  type: string
                  format: binary
              required:
                - document
            encoding:
              document:
                contentType: application/octet-stream
        required: true
      responses:
        "200":
          description: uploadDocument 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
  /document/upload-files:
    post:
      tags:
        - document
      operationId: uploadFiles
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                metadata:
                  type:
                    - string
                    - "null"
                  format: binary
                document:
                  type: string
                  format: binary
                instructions:
                  type:
                    - string
                    - "null"
                  format: binary
                schema:
                  type:
                    - string
                    - "null"
                  format: binary
              required:
                - document
            encoding:
              schema:
                contentType: application/octet-stream
              instructions:
                contentType: application/octet-stream
              metadata:
                contentType: application/octet-stream
              document:
                contentType: application/octet-stream
        required: true
      responses:
        "200":
          description: uploadFiles 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
  /job/result/{uuid}:
    get:
      tags:
        - job
      operationId: result
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: result 200 response
          content:
            application/json:
              schema:
                type: string
  /job/status/{guid}:
    get:
      tags:
        - job
      operationId: status
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: status 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProcessingJob"
  /settings/view:
    get:
      tags:
        - settings
      operationId: settings
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: settings 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
  /template/fill/{name}:
    post:
      tags:
        - template
      operationId: fill
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemplateFillRequest"
        required: true
      responses:
        "200":
          description: fill 200 response
          content:
            application/msword:
              schema:
                type: string
                format: binary
            application/pdf:
              schema:
                type: string
                format: binary
  /template/list:
    get:
      tags:
        - template
      operationId: listTemplates
      responses:
        "200":
          description: listTemplates 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocumentTemplate"
  /template/metadata/{name}:
    get:
      tags:
        - template
      operationId: metadata
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: metadata 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PDFField"
  /template/{name}:
    post:
      tags:
        - document
      operationId: uploadTemplate
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                document:
                  type: string
                  format: binary
              required:
                - document
            encoding:
              document:
                contentType: application/octet-stream
        required: true
      responses:
        "200":
          description: uploadTemplate 200 response
          content:
            application/json:
              schema: {}
    delete:
      tags:
        - template
      operationId: deleteTemplate
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: deleteTemplate 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PDFField"
components:
  schemas:
    DocumentTemplate:
      properties:
        name:
          type: string
        organization:
          type:
            - "null"
            - object
          allOf:
            - $ref: "#/components/schemas/Organization"
        contenttype:
          type:
            - string
            - "null"
        created:
          type:
            - string
            - "null"
          format: date-time
        updated:
          type:
            - string
            - "null"
          format: date-time
      required:
        - name
    ExtractionMode:
      enum:
        - SIMPLE
        - STEPS
    LlmType:
      enum:
        - DEFAULT
        - MINI
        - PREMIUM
    NamedConfiguration:
      properties:
        id:
          type:
            - integer
            - "null"
          format: int64
        name:
          type: string
        organizationId:
          type: integer
          format: int64
        storagePath:
          type: string
        created:
          type:
            - string
            - "null"
          format: date-time
        updated:
          type:
            - string
            - "null"
          format: date-time
      required:
        - name
        - organizationId
        - storagePath
    OcrType:
      enum:
        - DEFAULT
        - PREMIUM
        - NONE
    Organization:
      properties:
        name:
          type: string
      required:
        - name
    PDFField:
      properties:
        name:
          type: string
        tooltip:
          type:
            - string
            - "null"
        type:
          type: string
        flags:
          type: array
          items:
            type: string
        value:
          type: string
        defaultValue:
          type:
            - string
            - "null"
        options:
          type: array
          items:
            type: string
        script:
          type:
            - string
            - "null"
      required:
        - flags
        - name
        - options
        - type
        - value
    ProcessingJob:
      properties:
        status:
          type: string
        guid:
          type: string
        error:
          type:
            - string
            - "null"
        tokenCount:
          type:
            - integer
            - "null"
          format: int32
        created:
          type:
            - string
            - "null"
          format: date-time
        updated:
          type:
            - string
            - "null"
          format: date-time
      required:
        - guid
        - status
    Settings:
      properties:
        apiKey:
          type: string
      required:
        - apiKey
    TemplateFillRequest:
      properties:
        fields:
          additionalProperties: true
      required:
        - fields
    Unit: {}
    UploadCommand:
      properties:
        ocr:
          type:
            - "null"
            - object
          allOf:
            - $ref: "#/components/schemas/OcrType"
        llm:
          type:
            - "null"
            - object
          allOf:
            - $ref: "#/components/schemas/LlmType"
        extractionMode:
          type:
            - "null"
            - object
          allOf:
            - $ref: "#/components/schemas/ExtractionMode"
        schema:
          type:
            - string
            - "null"
        prompt:
          type:
            - string
            - "null"
        barcodes:
          type:
            - boolean
            - "null"
        mimeType:
          type:
            - string
            - "null"
    UploadResponse:
      properties:
        guid:
          type: string
        status:
          type: string
      required:
        - guid
        - status
